services:
  fatrace-exporter:
    image: ghcr.io/joaocotralha/fatrace-exporter:main
    ports:
      - 8123:8123
    volumes:
      # target directory for monitoring
      - ${TARGET_DIRECTORY}:/mount
    restart: always